### ISSUE TITLE
Original image dimensions in preview?

### ISSUE THREAD

**Issue by masugadesign** [boboldehampsink/assetpreview#6]
Would it be possible to modify this plugin to add the original image dimensions in the preview? 

I'm not easily finding asset dimension information anywhere in the Craft CP. For example, I'd love to know if an uploaded image is 640 wide or 1800 wide, especially if we have similarly named images that otherwise look identical in the Asset directory.

**Comment by boboldehampsink** [comment]
Not easily, as this plugin is javascript only. You'd have to calculate the dimensions on the server side then send them to the client. It's a nice idea but not something I plan to do. A Pull Request is always welcome.

**Comment by masugadesign** [comment]
OK, understood. As is, this plugin is a step up from default Asset functionality, so thanks for releasing it!
